ignoredBlocks:
  - AIR
  - SAPLINGS
  - FLUIDS
  - RAILS_RELATIVED
  - REDSTONE_RELATIVED
  - DOORS
  - SIGNS
  - PLANTS
  - FLOWER_POTS
  - SKULLS
  - WEB
  - TORCH
  - FIRE
  - LADDER
  - SNOW
  - PORTAL
  - CAKE_BLOCK
  - CARPETS
  - BANNERS