name: TreeLogging
main: tw.davy.minecraft.treelogging.bukkit.TreeLoggingPlugin
version: 0.1.0
authors:
    - Davy
website: http://mc.davy.tw/plugins/TreeLogging
description: Makes logging trees truely.
commands:
    treelogging:
        description: Display TreeLogging's infomations.
        usage: /<command>
        permissions: 'treelogging.commands.info'
