name: TreeLogging
main: tw.davy.minecraft.treelogging.bukkit.TreeLoggingPlugin
version: 0.4.1
authors:
    - Davy
website: http://mc.davy.tw/plugins/TreeLogging
description: Makes logging trees truely.
commands:
    treelogging:
        description: Display infomations of TreeLogging.
        usage: /<command>
        permissions: 'treelogging.commands.info'
    tl:
        description: Execute commands of TreeLogging.
        usage: |
            /<command> command
            Command list:
                recording: Enable/Disable recording protecting trees.
        permissions: 'treelogging.commands.execute'
